Justfile
config/tools.yml

MPR has just @ 1.14, whereas github has it at 1.16.0
- remove just via apt remove after installing tools.

feat: add just via github

---

Justfile
README.md
bootstrap.sh
config/tools.yml

There's no point having the pip version of yq since it's not a direct transient dependency for gh-release-install.
Use the snap version of mikefarah/yq to bootstrap and remove it like we do 'just'
- use snap variant of yq to bootstrap
- install mikefarah/yq as yq
- add note about snap+systemd

feat: switch to snap yq

---

Justfile

It's kinda tiresome to have to install the everything again on any 
single binary update.
- add list of installed versions in ~/.config/ubuntu-dpm 
which is used to avoid constant downloads of the binaries
- remove pin recipe because 
alias j='just --justfile ~/.user.justfile --working-directory .'

feat: add cache of installed_versions

---

Justfile
README.md
config/tools.yml

Script the installation of various language version managers and install the 'latest' stable version of each of those languages.
Move `install_tfenv` into the sdk recipe and force the initial version of terraform there rather than in tools to avoid a needless abstraction leak.
- Add ruby/node/java/rust/go version managers
- Update docs to reflect usage change
- tfenv moved into 'sdk' recipe

feat!: add language version management

---

Justfile
config/tools.yml

Opentofu is now GA (1.6.0) and we can use tofuenv to manage the tofu versions. Since they are separate binaries both terraform & opentofu can of course live side-by-side.
- made 'install_tfenv' more generic
- made sdk recipes public

feat: add tofuenv to manage opentofu

---

Justfile
config/tools.yml

Most of the time both extract & binary are the same so merge them into a single key separated by :
making the assumption that : is unlikely to be a part of a filename
- remove extract key
- remove binary key
- new 'contents' key that is colon separated essentially becoming 'extract:binary'
- added minimal notes about keys to tools.yml

feat!: merge extract+binary keys

---

bootstrap.sh

Download all apt repo keys to `/usr/share/keyrings`.
- add helper function
- update locations of apt keyrings
- rename keys to be generic

refactor: use /usr/share/keyrings for all repo keys

---

bootstrap.sh

Add [`wslu`](https://github.com/wslutilities/wslu) for opening browsers from other cli (`gh auth`).
Skipped to Ubuntu as the package is already present on there builds.
- add wslutilities repo and keyring if WSL and Debian
- add wslu package if WSL and Debian

feat: add wslu only on Debian WSL

---

Justfile
config/tools.yml

Add `fzf` for a cli fuzzy finding, the version in Debian repo is quite far behind.
- Add fzf to tools.yml
```shell
if type fzf &>/dev/null; then
eval "$(fzf --bash)"
fi
```
After set-up there's some interesting scripts out there [fzf-git](https://github.com/junegunn/fzf-git.sh):
Add `fzf-tmux` which is required by `fzf-git`.
```shell
curl -L https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux -o ~/.local/bin/fzf-tmux
chmod +x ~/.local/bin/fzf-tmux
```
Checkout `fzf-git`:
```shell 
git clone git@github.com:junegunn/fzf-git.sh.git
```
```shell
if [ -e "$HOME/code/.../fzf-git.sh/fzf-git.sh" ]; then
source "$HOME/code/.../fzf-git.sh/fzf-git.sh"
fi
```

feat: add fzf for cli fuzzy finding

---

.github/workflows/shellcheck.yml
Justfile
README.md
bootstrap.sh

If SKIP_DOCKER is set then you can _never_ run `just tools`; so the requirement is to remove the use of docker to run `yq`
Since we are doing that, then we should reduce complexity by install oneshot tools like `just` in bootstrap.sh rather than adding the prebuilt repo unnecessarily.
- remove prebuilt_mpr as a repo
- install 'just' via gh-release-install
- install 'yq' in justfile via gh-release-install
- add systemctl mask or binfmt (for wslview)
- add shellcheck action
- wslutilities repo back behind a debian test
- force rustup to not modify profiles
- I tested with Debian, since my primary is Ubuntu (so I feel happier deleting Debian).
```powershell
wsl -t Debian
wsl --unregister Debian
wsl --install Debian
```
- Minimal bootstrapping : 
```bash
sudo apt-get update && sudo apt-get -y …
```

feat: cleanup tooling baseline

---

Justfile
README.md

We want to use fzf + fzf-git such that when we do `git commit --fixup` we can do a ctrl-gh and get a list of hashes we want to fix up, right in the terminal
(this is such a game changer!)
- add fzf-git justfile recipe to source fzf-git & fzf --bash
- fzf-git recipe does not update bashrc if DPM_SKIP_FZF_BASHRC is set
- add shellcheck directives to Justfile
- add git pull during 'just update'
`just fzf-git` - this nominally requires you to have fzf installed before it's meaningful
The results should be:
- should modify your .bashrc (if fzf / fzf-git) are not already in bashrc
- fzf-git.sh should be checked out into ~/.local/share/ubuntu-dpm/fzf-git.sh
- fzf-tmux should be present in ~/.local/bin

feat: add fzf-git as recipe

---

.github/workflows/updatecli.yml
Justfile
config/tools.yml

The `yamlpath` is basically the same for every configuration, so it should be default. Previously it was not defaulted because we weren't preserving the top level 'key'
Preserve the top level key by using `to_entries` and then changing the filter to get the appropriate information out of `.value.X` instead.
- preserve the 'key' by using 'to_entries'
- updatecli.yml workflow modified to match

feat: make yamlpath in tools.yml optional

---

README.md
bootstrap.sh

resolves #136
- refactor so that distro_name has a single exec
- shfmt -i 2 -w
- apt install bsdextrautils if debian

fix: add bsdextrautils if debian

---

.github/workflows/test.yml
Justfile
config/repos.yml

Installing tools for gh releases is one part of the bootstrapping process, we're now seeing the need to checkout and sometimes link repositories containing shell scripts.
- add repos.yml
- add bitbucket-pr to repos, including link
- refactor fzf-git.sh checkout to align with process
- update workflow on to stop duplication
Remove an existing link for `bb-pr` is applicable
```shell
just tools
ls -l ~/.local/share/ubuntu-dpm/
type bb-pr
ls -l  ~/.local/bin/bb-pr
```

feat: add the ability to checkout and link scripts

---

Justfile

Since we no longer use snap or just from mpr we don't need to log about it.
- remove snap_apt variable use + logging
It should no longer have the `>>> you might want to run hash -r` logging between the last binary tool install, and the repo checkout/update.
```bash
bsh ❯ rm -rf ~/.config/ubuntu-dpm/installed-versions
bsh ❯ rm -rf ~/.local/shared/ubuntu-dpm/junegunn  ~/.local/shared/ubuntu-dpm/quotidian-ennui
bsh ❯ just tools
[+] just@1.25.2 from casey/just (attempt install)
[+] kubectx@v0.9.5 from ahmetb/kubectx (attempt install)
[+] k9s@v0.32.4 from derailed/k9s (attempt install)
[+] terraform-docs@v0.17.0 from terraform-docs/terraform-docs (attempt install)
[+] nova@v3.8.0 from fairwindsops/nova (attempt install)
[+] updatecli@v0.75.0 from updatecli/updatecli (attempt install)
[+] …
```

refactor: remove just/yq installation logging

---

Justfile
README.md

resolves #135
- add 'DPM_SKIP_JAVA_PROFILE' to skip sdkman mods
- add 'DPM_SKIP_NVM_PROFILE' to skip nvm mods
- add 'DPM_SKIP_RVM_PROFILE' to skip rvm mods
- add 'DPM_SKIP_RUST_PROFILE' to skip rust mods
- remove pin-github-action && prettier from npm i -g post nvm
BREAKING CHANGE: rustup now defaults back to modifying .bashrc but slightly differently to rustup defaults. We no longer install pin-github-action / prettier globally; use npx to execute them instead.
We always run rustup with --no-modify-paths because it actually scattergun modifies all your profiles. Prefer to have a `[[ -s "$HOME/.cargo/env" ]] &&` style so that we don't break if we share our profiles across systems via rcm or similar.

feat!: add ability to skip profile modification

---

bootstrap.sh

resolves #134
This is the link for adding mantic & noble (code block to avoid spam).
```
https://github.com/aquasecurity/trivy/pull/6573
https://github.com/aquasecurity/trivy-repo/pull/36
```
- add fallback dist name for ubuntu & debian
```
wsl --install Ubuntu-24.04
...
./bootstrap.sh repos
```
- `/etc/apt/sources.list.d/trivy.list` should refer to jammy, and not noble.

feat: add fallback support for trivy apt repo

---

Justfile
README.md
config/repos.yml
config/sdk.yml
config/tools.yml
updatecli.d/sdk-gradle.yml
updatecli.d/sdk-jbang.yml
updatecli.d/sdk-maven.yml
updatecli.d/sdk-nvm.yml
updatecli.d/sdk-opentofu.yml
updatecli.d/sdk-ruby.yml

resolves #138 
- switch to an explicit 'sdk.yml' with versions
- remove use of gh release list in justfile
- promote configure_ghcli to a top level recipe as 'ghcli'
- remove DPM_SKIP_GHCLI_CONFIG since it is redundant
- add updatecli configuration for sdk artifacts
- remove terraform install from 'sdk all'
BREAKING CHANGE: tofu|terraform versions moved from tools.yml to sdk.yml. terraform no longer installed by default by 'sdk all'
`$.sdkman.java` doesn't have a corresponding updatecli configuration because at the moment updatecli doesn't have anything similar to `ignore this major version` style functionality, and it will always push us to update to the latest version, even though we want to pin to a java LTS.
> Not exactly happy with updatecli.d/* should be possible to merge that into …

feat!: remove dependency on ghcli at runtime

---

Justfile
README.md

Add the ability to add your own tools and repos on top of the existing ones, arguably more useful for repos with dotfiles and other things.
- add two new properties DPM_TOOLS_ADDITIONS_YAML and DPM_REPO_ADDITIONS_YAML
- creates an array of files that is passed onto yq command
- using yq before processing merge additional yaml with base yaml
```shell
printf 'config/repos-additions.yml' | tee -a .git/info/exclude 
printf 'gitscripts:
repo: mcwarman/gitscripts
' | tee -a config/repos-additions.yml
printf 'export DPM_REPO_ADDITIONS_YAML="./config/repos-additions.yml"' | tee -a .envrc
just tools
```

feat: add ability to extend config

---

.github/workflows/test.yml

#152 didn't add any tests; so let's do that based on the PR comments
- add repo-additions test (mcwarman/gitscripts)
- add tools-additions test (yannh/kubeconform)

test: add tests for config extension

---

.github/workflows/test.yml
Justfile
README.md
config/sdk.yml
config/tools.yml
updatecli.d/sdk-golang.yml

`ankitcharolia/goenv` seems to be a global goenv style tool. Isn't shell instance specific, or even directory specific. It also requires us to have done `just tools` first.
An alternative that is being updated is `go-nv/go-env` which is different. It is possible for both  to potentially live in harmony with each other, so we can install them side by side.
ankitcharolia/goenv becomes what go-nv/go-env thinks is the system go...
- add 'sdk goenv install' to install goenv & golang
- add 'sdk goenv update' to update go-nv/goenv repo
- remove 'sdk go' from 'sdk all'
- golang version explicitly defined in config/sdk.yml
BREAKING CHANGE: 'sdk all' no longer installs a golang version manager, the user has to make
an explicit choice.
Since go-nv doesn't have the same concept of `--list-remotes` …

feat(go)!: add go-nv/goenv

---

.github/workflows/shellcheck.yml
.github/workflows/updatecli.yml
Justfile
bootstrap.sh
src/main/scripts/common.sh
src/main/scripts/configure_ghcli.sh
src/main/scripts/fzf-git.sh
src/main/scripts/init_direnv.sh
src/main/scripts/install_repos.sh
src/main/scripts/install_tools.sh
src/main/scripts/is_supported.sh
src/main/scripts/just_help.sh
src/main/scripts/sdk_install_aws.sh
src/main/scripts/sdk_install_go.sh
src/main/scripts/sdk_install_goenv.sh
src/main/scripts/sdk_install_java.sh
src/main/scripts/sdk_install_nvm.sh
src/main/scripts/sdk_install_rust.sh
src/main/scripts/sdk_install_rvm.sh
src/main/scripts/sdk_install_sonar_scanner.sh
src/main/scripts/sdk_install_tvm.sh
src/main/scripts/updatecli.sh

It is getting to the stage where a monolithic justfile probably isn't great; especially since we have to duplicate functions (yq_wrapper).
Push all the inline scripts as external scripts in src/main/scripts. 
This is the first part of a 2stage PR, the second will be to merge all the sdk_* into a single script...
- switch to external scripts not inline
- modify updatecli workflow to use script
- add shellcheck on all scripts

refactor: switch to external scripts not inline

---

README.md
src/main/scripts/common.sh
src/main/scripts/fzf-git.sh
src/main/scripts/includes/install_archives
src/main/scripts/includes/sdk_install_goenv
src/main/scripts/includes/sdk_install_rust

- Resolves #268
- Defaults to $HOME/.bashrc
- add DPM_BASH_PROFILE_FILE env-var taht defaults to $HOME/.bashrc
- fixes a typo from #259 
Only modifies things where we directly modify bashrc; NPM/RVM will continue doing what they do.
```console
bsh ❯ just fzf-git
>>> Added fzf --bash to /home/lchan/.bashrc
>>> Added fzf-git.sh to /home/lchan/.bashrc
bsh ❯ just sdk goenv install
Already up to date.
>>> DPM automatically added goenv to /home/lchan/.bashrc
* 1.22.5 (set by /home/lchan/.goenv/version)
bsh ❯ just sdk rust
info: downloading installer
...
>>> DPM automatically added .cargo/env to /home/lchan/.bashrc
bsh ❯ just install archives
[+] joelittlejohn/jsonschema2pojo (attempt install)
[+] quotidian-ennui/parquet-cli-wrapper (attempt install)
[~] …
```

feat: add env-var to specify bash profile

---

config/tools.yml

Because you might want to do `lnav docker://plantuml` (or similar) see https://github.com/tstack/lnav
- add tstack/lnav

feat: add tstack/lnav

---

updatecli.d/sdk-golang.yml

updatecli often detects golang release before goenv has had a chance to update itself (goenv updates nightly with the list of releases). This leads to the situation where the `install-goenv` github action test fails because of timings.
Add a condition to updatecli to curl the corresponding file that goenv will update itself with (pyenv does a similar thing).
- add an updatecli condition using shell+curl

fix(ci): add condition to golang check

---

src/main/scripts/includes/sdk_install_all
src/main/scripts/includes/sdk_install_help

Because of https://github.com/quotidian-ennui/ubuntu-dpm/pull/271 we can now install go via go-nv/goenv for convenience since you don't have to make a choice.
- add pyenv to sdk all
- add goenv to sdk all

feat: add pyenv and goenv to sdk all

---

Justfile
config/updatecli.yml
src/main/scripts/updatecli.sh

Running `just updatecli` doesn't support any local tools that you have.
- add ability to run updatecli against DPM_TOOLS_ADDITIONS_YAML
- You should now be able to update any tools that you want to use but aren't in config/tools.yml
- No change to existing github workflow (i.e. running ./src/main/scripts/updatecli.sh apply still just works).
- Create an extras.yml that contains something like (12.1.1 is the previous version)
```
tokei:
repo: XAMPPRocky/tokei
version: v12.1.1
artifact: tokei-x86_64-unknown-linux-musl.tar.gz
contents: tokei
```
- `export DPM_TOOLS_ADDITIONS_YAML=/..../extras.yml`
- `just updatecli local` -> should just check tokei is uptodate
- `just updatecli upstream` -> should check the things in config/tools.yml, _upstream_ can be any string other than …

feat: add updatecli capability for local tools

---

src/main/scripts/includes/sdk_install_help
src/main/scripts/includes/sdk_install_java

You already have sdkman installed, and you don't want to install it again, and all the packages. You just want to upgrade a single sdkman candidate and remove the previous version. This is often true if you're upgrading a build tool like gradle/maven etc. 
You could run `sdkman upgrade` directly, but you are lazy and you don't want to have to run `sdk uninstall xxx 1.2.3` afterwards.
- add upgrade capability with post upgrade deletion of previous.
Let's say you have liquibase 4.29.0 installed, now you can do this:
```shell
bsh ❯ just sdk java upgrade liquibase
No update available at this time.
No new candidates found at this time.
Available defaults:
liquibase (local: 4.29.0; default: 4.29.2)
Downloading: liquibase 4.29.2
In progress...
Installing: liquibase 4.29.2
Done installing! …
```

feat: add update of individual sdkman candidates.

---

src/main/scripts/includes/sdk_install_java

Because of https://github.com/quotidian-ennui/ubuntu-dpm/pull/367#discussion_r1781146640 then if we are already in auto-answer=true then don't reset it to be false at the end of operations.
- check auto-answer state before resetting it
Modify ~/.sdkman/etc/config and set auto_answer=true; then run an upgrade, auto_answer should still be true.

fix: preserve sdkman auto-answer mode

---

config/tools.yml

I thought it was always included in my baseline toolset; imagine my surprise when it wasn't.
- add joerdav/xc

feat: add joerdav/xc

---

config/sdk.yml
src/main/scripts/includes/sdk_install_aws
updatecli.d/sdk-amazon-ecr-credential-helper.yml

Add [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) as a part of `just sdk aws`
This means you don't have to do 
```shell
aws ecr get-login-password | docker login --username AWS "<registry>"
```
Once set up `docker pull ...` works.
- add download function for amazon-ecr-credential-helper
- add updatecli config to keep version up to date

feat(sdk-aws): add ecr docker credential helper

---

src/main/scripts/includes/install_archives

- `rcup` means I (might) end up sharing my .bashrc file across machines
- I installed wvlet on my laptop, but not on my desktop
- I felt sad when wvlet appeared when I did "echo $PATH" on my desktop
- add directory detection before path addition
```
export DPM_ARCHIVES_ADDITIONS_YAML=..../extra_archives.yml
echo '
wvlet:
repo: wvlet/wvlet
version:
github_tag: v2024.9.7
strip_prefix: v
artifact: "wvlet-cli-{version}.tar.gz"
extract: "wvlet-cli-{version}"
runtime:
path_addition:
- "{root}/bin"
' >> .../extra_archives.yml
just install archives
tail -n 2 ~/.bashrc
[[ -d "/home/lchan/.local/share/ubuntu-dpm/wvlet/wvlet/bin" ]] && PATH=$PATH:/home/lchan/.local/share/ubuntu-dpm/wvlet/wvlet/bin
```

refactor(archives): slightly better path mangling

---

.github/workflows/test.yml
config/archives.yml
src/main/scripts/includes/sdk_install_all
src/main/scripts/includes/sdk_install_help
src/main/scripts/includes/sdk_install_tvm

Well, why install install 2 managers, when you can just install one; now that we can install an archive and edit the path (which we couldn't before with gh-release-install) we can just install
the tar.gz of tenv and use it.
- add tenv as an install via 'archives'
- add just sdk tvm tenv
BREAKING-CHANGE: tofuenv is no longer installed as part of 'just sdk all'
```console
rm -rf ~/.tfenv
rm -rf ~/.tofuenv
rm -f ~/.local/bin/terraform ~/.local/bin/tofu ~/.local/bin/tofuenv ~/.local/bin/tfenv
just install archives
which tenv  # might need to restart your shell / source .bashrc
just sdk tvm tenv
```

feat!: add tenv to support terraform and opentofu

---

src/main/scripts/includes/sdk_install_help
src/main/scripts/includes/sdk_install_pyenv

On a new debian instance trying to install pyenv; it failed because of a missing C compiler...
- add check for build-essential and install if not
- add explicit prepare subcommand 'sdk pyenv prepare'
> Could do an `apt list --installed | grep ` and check exit code but I'm not sure what to grep for since it's a lot of packages; and we don't want to install them if we don't care about python?
```
sudo apt remove g++
sudo apt autoremove
pyenv remove 3.12.7 (if you have it)
just sdk pyenv install
```

refactor(pyenv): add build-essential for pyenv

---

config/sdk.yml
src/main/scripts/includes/sdk_install_java
updatecli.d/sdk-java.yml

graalvm-ce 21.0.2 will never be updated (since graalvm-ce is the community edition) which means we are potentially missing out on the fixes for 0.3 / 0.4 / 0.5
We want a jdk that is
- available via sdkman
- marked as a github release, so that we can updatecli it
- (stops us from having to triage non LTS releases since I don't want to run JDK23+ until JDK25 is available).
so the options were
- temurin: https://github.com/adoptium/temurin21-binaries for temurin (`jdk-(\\d*\\.\\d*\\.\\d*).*$`)
- corretto: https://github.com/corretto/corretto-21 (`^(\\d*\\.\\d*\\.\\d*).*$`)
- liberica: https://github.com/bell-sw/Liberica (`^(\\d*\\.\\d*\\.\\d*).*$`) but the repo has all the java versions.
- mandrel doesn't really follow the same LTS naming cycle
- zulu java doesn't have a github project (this …

refactor(java)!: switch default JDK from graalvm to corretto

---

updatecli.d/sdk-java.yml

Because updatecli change the semantics of regex/semver
- add findsubmatch transformer to strip extended versioning

fix(updatecli): add transformer for java/correto to strip extended version

---

src/main/scripts/includes/sdk_install_help
src/main/scripts/includes/sdk_install_java

Sometimes you just want to reset java versions to what they are in the configuration file.
- add reset command to java helper
- refactor base install to use a for loop
Since gradle currently hasn't been updated to 8.12 you should be able to do this 
```bash
just sdk java upgrade gradle
just sdk java reset gradle
```
Similarly, because 21.0.6-amzn is 'new' you could do `just sdk java reset java`

feat(sdk): add reset as a sub-command to java helper

---

Justfile
bootstrap.sh

Really should switch to using the Microsoft APT repo to install vscode on my linux laptop.
- add explicit bootstrap.sh desktop
- add autoremove post apt upgrade

refactor: add explicit desktop bootstrap

---

config/archives.yml

- don't use jsonschema2pojo so remove it
- remove jsonschema2pojo
- make parquet-cli a symlink
> There is no uninstall so we have to manually fudge it so that we test as though we were new.
- remove parquet cli from the path (~/.bashrc) if it's in there.
- remove jsonschema2pojo symlink from ~/.local/bin
- remove jsonschema2pojo from ~/.local/share/ubuntu-dpm
- edit ~/.config/ubuntu-dpm/installed-versions to remove parquet-cli
- just install archives -> no jsonschema2pop, but new symlink for parquet

refactor!: remove jsonschema2pojo
